### ISSUE TITLE
absolute path link to assets

### ISSUE THREAD

**Issue by SteveVallay** [obviam/star-assault#1]
Hi, Tamas :
Thanks a lot for your excellent tutorial on your blog, really learned a lot from it. 
Seem in this project you have used an absolute path link in star-assault-desktop  to the resource file in star-assault-android/assets , it shows as an absolute path as: 
<location>/Users/tamas/Documents/workspace.juno/obviam/star-assault/star-assault-android/assets</location>
This won't work for others. It cost me some time to find this.So hope others can konw this.
Do you think copy the resources to star-assault-desktop is a good solution ?

**Comment by obviam** [comment]
Hi there,

Thank you for pointing it out. I thought I used the variables in eclipse to
work out the relative path for the current structure.
I also noticed that there is a pull request to fix it and I will approve
it.

Many thanks again,
Tamas
